backend:
  name: github
  repo: grey-highroads/decap-test-site
  branch: main
  base_url: https://decap-test-site.pages.dev

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Homepage"
        name: "homepage"
        file: "content/homepage.yml"
        fields:
          - label: "Headline"
            name: "headline"
            widget: "string"

          - label: "Button Link"
            name: "button_link"
            widget: "string"
